trading_bot:
  target: default
  outputs:
    default:
      type: duckdb
      path: "{{ env_var('DATA_ROOT') }}/catalog.duckdb"
      extensions:
        - parquet
      external_root: "{{ env_var('DATA_ROOT') }}"
