version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: "ep_redis"
    ports:
      - "6379:6379"
    volumes:
      - ${HOST_REDIS_PATH}:/data
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --protected-mode no
    networks:
      - trading_net
    restart: unless-stopped
  
  # Microservices
  oanda_listener:
    container_name: "ep_oanda_listener"
    build:
      context: .
      dockerfile: services/oanda_listener/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - trading_net
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ACCOUNT_ID=${ACCOUNT_ID}
      - API_TOKEN=${API_TOKEN}
      - INSTRUMENTS=${INSTRUMENTS}
      #- OANDA_ENV=${OANDA_ENV}

  stream_writer:
    container_name: "ep_stream_writer"
    build:
      context: .
      dockerfile: services/stream_writer/Dockerfile
    restart: unless-stopped
    volumes:
      - ${HOST_DATA_PATH}:/data
    depends_on:
      - redis
    networks:
      - trading_net
    environment:
      - PYTHONUNBUFFERED=1
      - LANDING_DIR=/data/landing/ticks
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  compactor_ingestor:
    container_name: "ep_compactor_ingestor"
    build:
      context: .
      dockerfile: services/compactor_ingestor/Dockerfile
    restart: unless-stopped
    volumes:
      - ${HOST_DATA_PATH}:/data
    networks:
      - trading_net
    environment:
      - LANDING_DIR=/data/landing/ticks
      - BRONZE_DIR=/data/bronze/ticks
      - PYTHONUNBUFFERED=1
    

networks:
  trading_net:
    driver: bridge
      