name: "trading_bot"
version: "1.0.0"
profile: "trading_bot"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  trading_bot:
    # Default config for Silver Layer
    silver:
      +materialized: external
      +location: "silver/{name}.parquet" # Auto-saves as silver/filename.parquet

    # Default config for Gold Layer
    gold:
      +materialized: external
      +location: "gold/{name}.parquet"
