trading_bot:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    prod:
      type: duckdb
      path: "/data/catalog.duckdb"
      extensions:
        - parquet
      settings:
        external_root: "/data"
      vars:
        bronze_path: "/data/bronze"

    dev:
      type: duckdb
      path: "./dev_data/catalog.duckdb"
      extensions:
        - parquet
      settings:
        external_root: "./dev_data"
      vars:
        bronze_path: "./dev_data/bronze"
